# Generated by Django 2.2 on 2020-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='infection_rate',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
